
[webservers]
web-1 ansible_host=62.84.117.60 fqdn=fhm3f17ncrli5mht2g61.auto.internal
web-2 ansible_host=89.169.151.222 fqdn=fhmtgfvciodj1n2sl8g2.auto.internal

[databases]
db-main ansible_host= fqdn=fhmtde000ekev5n91g15.auto.internal
db-replica ansible_host= fqdn=fhm0acrhoa0iqahj6gob.auto.internal

[storage]
storage ansible_host=89.169.149.88 fqdn=fhmbv302qbnl4e0b0d3a.auto.internal
