
[webservers]
web-1 ansible_host=178.154.207.171 fqdn=fhma3g4gmmcs175r7nge.auto.internal
web-2 ansible_host=178.154.220.225 fqdn=fhmdspmrlsjjevbsa5m4.auto.internal

[databases]
db-main ansible_host= fqdn=fhmla00rnhtf4fle19q7.auto.internal
db-replica ansible_host= fqdn=fhm7535sbi22j8unucb2.auto.internal

[storage]
storage ansible_host=178.154.220.241 fqdn=fhmlgtctrsj8ca3cgt83.auto.internal
